# -*- coding: utf-8 -*-
"""instruction-text.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZKwm31zGVP-GBZTZ8AsQPmgXnLV5jJ6h
"""

from transformers import set_seed
import pandas as pd
import matplotlib.pyplot as plt
from collections import Counter
import numpy as np
import random
import torch

"""three fields in each prompt: question, bot, task

input to the model is:
```
<s>human
[question]
<s>bot
[bot]
```
where a question is
```
[program]

[question]
```
"""

in_dir = "data/pretrain"
downstream_buggy = "data/train.buggy-fixed.buggy"
downstream_fixed = "data/train.buggy-fixed.fixed"
out_dir = "data_sample"
no_return_sample_num = 20
max_rows = 50  # limit rows read from each file
max_downstream = 50  # limit Java bug-fix samples

# auto-detect available lang/graph combinations
import os
available_combos = []
for lang in ['Java', 'Python']:
    for graph in ['DFG', 'AST']:
        if os.path.exists(f"{in_dir}/{lang}_{graph}.jsonl"):
            available_combos.append((lang, graph))
print(f"Found: {available_combos}")

# accumulate results across all sections
graph_dfs = []   # keeps node_ids, edge_index, question, bot

figsize = (24, 16)
fontsize = 28
fontsize_tick = 16

def filter_df(df, n=None):
    try:
        n = n if n is not None else no_return_sample_num
        return pd.concat([df[df.source.apply(lambda x: 'return ' in x)], df[df.source.apply(lambda x: 'return ' not in x)].sample(n)]).reset_index(drop=True)
    except:
        return df

def capitalize(s: str):
    return s[0].upper() + s[1:]

def replace_digit(s: str):
    return s.replace('10', 'ten').replace('1', 'one').replace('2', 'two').replace('3', 'three').replace('4', 'four').replace('5', 'five').replace('6', 'six').replace('7', 'seven').replace('8', 'eight').replace('9', 'nine')

def print_df(df, n=10):
    for i in range(n):
        print(df.loc[i].question)
        print(df.loc[i].bot)
        print('---'*10)

graph_type_map = {'AST': 'abstract syntax tree', 'DFG': 'data flow graph'}
NODE_TYPES = [
    'assignment expression',
    'basic block',
    'binary expression',
    'break statement',
    'call expression',
    'catch clause',
    'class expression',
    'compile unit',
    'conditional expression',
    'continue statement',
    'export statement',
    'for statement',
    'function expression',
    'identifier expression',
    'if statement',
    'import expression',
    'key value parameter',
    'literal expression',
    'member access',
    'new expression',
    'new with type expression',
    'object expression',
    'object property',
    'parameter',
    'Python delete',
    'Python with',
    'Python with expression clause',
    'Python yield expression',
    'range statement',
    'return statement',
    'scope',
    'spread collection expression',
    'spread dictionary expression',
    'super expression',
    'switch case',
    'switch statement',
    'this expression',
    'throw statement',
    'try statement',
    'tuple expression',
    'unary expression',
    'variable declaration',
    'while statement'
]

# ph stands for place holder
ph1 = 'aohg981thgboir2bnjosi1839r8g9udnfv,mqwfo'
ph2 = 'io12i3ru9ginal90109ja-efi1-3gasd130gn0wa9'
ph3 = '2091rng09wegnb2p09jojmpzf,k[2e00-jmaa]'
ph4 = '0391gnea-g0-jr0aegbm[afk0-249jgps]waeg0'
ph5 = 'io1hngi0enriqgpgv]139gonpiamofj10onem;alf'
ph_list = [ph1, ph2, ph3, ph4, ph5]
punc_list = [",", "?", ".", ";", "'s"]

def replace_place_holder(s, node_text, placeholder="{node}"):
    # this function injects a multi-line code snippet into the template

    if placeholder not in s:
        return s

    # 1. remove the white spaces around {node} placeholder
    s = s.replace(f"{placeholder} ", f"{placeholder}").replace(f" {placeholder}", f"{placeholder}")
    for punc in punc_list:
        s = s.replace(f"{placeholder}{punc} ", f"{placeholder}{punc}")

    # 2. injects the code, but first replace patterns like '\n.' in both the code and template (the template may contain previously injected code)
    for ph, punc in zip(ph_list, punc_list):
        node_text = node_text.replace(f"\n{punc}", ph)
        s = s.replace(f"\n{punc}", ph)
    s = s.replace(placeholder, node_text)

    # 3. replace patterns like "\n." caused by the template
    for punc in punc_list:
        s = s.replace(f"\n{punc}", f"{punc}\n")

    # 4. replace the placerholders inserted in step 2
    for ph, punc in zip(ph_list, punc_list):
        s = s.replace(ph, f"\n{punc}")
    return s

"""## node classification"""

questions = [
    'In the {graph} of this {lang} program, what is the type of this node: {node}.',
    'Tell me the node type of {node} in the {graph} of this {lang} program.',
    'What is the node type of {node} in the {graph} of this {lang} program',
    "In the {graph} of the provided {lang} program, could you identify the type of the node {node}?",
    "What kind of node is {node} in the {graph} of this {lang} program?",
    "Can you classify the node {node} in the {graph} of this {lang} program?",
    "What category does the node {node} fall under in the {graph} of this {lang} program?",
    "Regarding the {graph} of this {lang} program, what is the classification of the node {node}?",
    "In the context of the {graph} of this {lang} program, what is the nature of the node identified as {node}?",
    "Could you tell me what the node {node} represents in the {graph} of this {lang} program?",
    "I'm curious, what type of node is {node} in the {graph} of the {lang} program presented?",
    "What is the designation of the node {node} within the {graph} of this {lang} program?",
    "Could you specify the node type for {node} in the {graph} of this particular {lang} program?",
    'Determine the node type of {node} in the {graph} of this {lang} program.',
]
answers = [
    "This node, {node}, is classified as a {answer}.",
    "The node {node} is a {answer}.",
    "This node is identified as a {answer}.",
    "It's a {answer}.",
    "Regarding the node {node}, it falls under the category of a {answer}.",
    "{node} is classified as a {answer} in the {graph} of this program.",
    "The classification of the node {node} is a {answer}.",
    "Within the {graph} of this program, {node} is a {answer} type of node.",
    "As for the node identified as {node}, it's considered a {answer}.",
    "The node {node} is of the {answer} variety.",
    'The type of this node is {answer}.',
    'The given node is a {answer}.',
    "{answer}.",
    "{answer}",
]
print(len(questions), len(set(questions)))
print(len(answers), len(set(answers)))
assert all(a.count('{answer}') == 1 for a in answers)
assert all(a.count('{graph}') == 1 for a in questions)
assert all(a.count('{lang}') == 1 for a in questions)

bots = [a for a in answers]
prompts = [[q, b] for q in questions for b in bots]
print(len(prompts))

set_seed(0)
results = {}
for lang, graph in available_combos:
        result = []
        df = pd.read_json(f"{in_dir}/{lang}_{graph}.jsonl", lines=True, nrows=max_rows)
        if lang == 'Python':
            df = filter_df(df)

        question, bot = [], []
        for i in range(len(df)):

            # filter out nodes that occur multiple times in the source code
            node_texts = df.loc[i]['text']
            node_ids = df.loc[i]['node_ids']
            source = df.loc[i]['source']
            assert len(node_ids) == len(node_texts)

            occurrences = np.array([source.count(t) for t in node_texts])
            nodes_single_occurrence = np.where(occurrences == 1)[0]

            # we sample 1 node from each program
            nodes = np.random.choice(nodes_single_occurrence, 1)
            for node in nodes:
                node_text = node_texts[node]
                node_id = node_ids[node]
                node_type = NODE_TYPES[node_id]

                p = random.sample(prompts, 1)[0]
                p = [s.replace('{graph}', f"{graph_type_map[graph]}").replace('{lang}', f"{lang}") for s in p]

                response = p[1]
                # deal with answer first in the response before plugging in the node text to avoid replacing something in the code
                if any(node_type.startswith(l) for l in 'aeio'):
                    response = response.replace(' a ', ' an ')
                response = response.replace('{answer}', node_type)
                response = capitalize(response)

                if '\n' in node_text:
                    node_text = f"\n```\n{node_text}\n```\n"
                    assert ph1 not in node_text and ph2 not in node_text and ph3 not in node_text and ph4 not in node_text and ph5 not in node_text
                    q = replace_place_holder(p[0], node_text)
                    response = replace_place_holder(response, node_text)
                else:
                    node_text = f"`{node_text}`"
                    q = p[0].replace('{node}', node_text)
                    response = response.replace('{node}', node_text)

                source = source.strip('\n')
                q = f"```\n{source}\n```\n\n{q}"
                question.append(q)
                bot.append(response)
                result.append(node_id)

        df['question'] = question
        df['bot'] = bot
        graph_dfs.append(df[['node_ids', 'edge_index', 'question', 'bot']])
        results[f"{lang}-{graph}"] = result

"""## parent node"""

questions = [
    'In the {graph} of this {lang} program, what is the parent node of this {node_type}: {node}.',
    'What is the parent of {node_type} {node} in the {graph} of this {lang} program?',
    'What is the parent node of {node_type} {node} in the {graph} of this {lang} program?',
    'Based on the {graph} of this {lang} program, identify the parent of {node_type} {node}.',
    'Based on the {graph} of this {lang} program, identify the parent of this {node_type}: {node}.',
    'Identify the parent of {node_type} {node} in the {graph} of this {lang} program.',
    "In the {graph} of the {lang} program presented, what is the predecessor of {node_type} {node}?",
    "What node acts as the parent to {node_type} {node} in the {graph} of the displayed {lang} program?",
    "Can you determine the parent node of {node_type} {node} in the {graph} of this {lang} program?",
    "Which node is directly above {node_type} {node} in the hierarchy of the {graph} of the provided {lang} program?",
    "Whose child is {node_type} {node} within the {graph} of this {lang} program?",
    "What is the immediate ancestor of the {node_type} {node} in the {graph} of this {lang} program?",
    "Regarding the {graph} of this {lang} program, can you point out the parent of {node_type} {node}?",
    "In terms of graph theory, what is the parent of the {node_type} {node} in the {graph} of this {lang} program?",
    "Who has the parental role for {node_type} {node} in the {graph}'s topology of this {lang} program?",
    "For {node_type} {node} in the {graph} of the given {lang} program, which node supplies the incoming edge?",
]
answers1 = [
    "In the {graph} of the given {lang} program, the parent of the given {node_type} is {parent}, which is a {parent_type}.",
    "This {node_type}'s parent is the {parent_type} {parent}.",
    "The given {node_type}'s parent in the {graph} of this {lang} program is the {parent_type} {parent}.",
    "The parent of {node_type} {node} in the {graph} of this {lang} program is identified as {parent}, categorized as a {parent_type}.",
    "In the structure of the {graph} of this {lang} program, {node_type} {node} finds its parent in node {parent}, which is a {parent_type}.",
    "Node {parent}, a {parent_type}, serves as the parent to {node_type} {node} in the {graph} of this {lang} program.",
    "As per the hierarchy in the {graph}, the {parent_type} node {parent} is the direct predecessor to {node_type} {node}.",
    "Upon inspection, it is clear that the parent of {node_type} {node} is the {parent_type} {parent}.",
    "The {node_type} {node} is immediately descended from {parent}, a {parent_type} in the {graph} of this {lang} program.",
    "{node_type} {node}'s parental node is determined to be {parent}, which falls into the category of {parent_type}.",
    "For {node_type} {node}, its lineage traces back to the {parent_type} node {parent} as its parent.",
    "Within the nodal arrangement of the {graph}, {parent} is the progenitor to {node_type} {node}, having the classification of a {parent_type}.",
    "Tracing the edges leads to confirming {parent}, a {parent_type}, as the parent of {node_type} {node}."
]
answers2 = [
    'This {node_type} has no parent in the {graph} of this {lang} program.',
    'This {node_type} has no parent in the {graph} of the given {lang} program.',
    'There is no edge pointing to this {node_type} in the {graph}. Therefore it does not have any parent.',
    'There is no edge pointing to this {node_type} in the {graph} of the given {lang} program. Therefore it does not have any parent.',
    "Within the confines of the {graph} of this {lang} program, {node_type} {node} does not have a parent node.",
    "{node_type} {node} stands without a parent in the {graph}'s structure.",
    "No parent node is associated with {node_type} {node} in the {graph} of the provided {lang} program.",
    "A review of the code establishes that there is no preceding node to {node_type} {node} in the {graph}; it has no parent.",
    "The {node_type} designated as {node} appears to lack a parental connection within the {graph} of this code.",
    "In terms of graph topology, {node_type} {node} is an orphan node with no parent.",
    "There is no edge incoming to {node_type} {node}, indicating the absence of a parent in the {graph} of this {lang} program.",
    "After analyzing the code, it becomes evident that {node_type} {node} lacks a directly linked parent node in the {graph}.",
    "The {graph} denotes that {node_type} {node} is disconnected from any parental lineage.",
    "As depicted in the code, {node_type} {node} exists without a parent node to claim in the {graph}.",
]
answers3 = [
    "There are multiple parents of this {node_type} in the {graph}:\n",
    "This {node_type} has more than one parent in the {graph}:\n"
]
print(len(questions), len(set(questions)))
print(len(answers1), len(set(answers1)))
print(len(answers2), len(set(answers2)))
print(len(answers3), len(set(answers3)))
assert all(a.count('{graph}') == 1 for a in questions)
assert all(a.count('{lang}') == 1 for a in questions)

bots = [a for a in answers1]
bots_none = [a for a in answers2]
bots_multiple = [a for a in answers3]
prompts = [[q, b] for q in questions for b in bots]
print(len(prompts))

set_seed(1)

results = {}
for lang, graph in available_combos:
        result = []
        df = pd.read_json(f"{in_dir}/{lang}_{graph}.jsonl", lines=True, nrows=max_rows)
        if lang == 'Python':
            df = filter_df(df)

        question, bot = [], []
        for i in range(len(df)):

            # filter out nodes that occur multiple times in the source code
            node_texts = df.loc[i]['text']
            node_ids = df.loc[i]['node_ids']
            source = df.loc[i]['source']
            edge_index = torch.tensor(df.loc[i]['edge_index'])
            assert len(node_ids) == len(node_texts)

            occurrences = np.array([source.count(t) for t in node_texts])
            nodes_single_occurrence = np.where(occurrences == 1)[0]
            nodes_with_parents = [n for n in nodes_single_occurrence if n in edge_index[:, 1]]
            nodes_without_parents = [n for n in nodes_single_occurrence if n not in edge_index[:, 1]]

            # we roughly maintain a balanced distribution
            if random.random() < 0.75 and len(nodes_with_parents) > 0:
                node = random.sample(nodes_with_parents, 1)[0]
            elif len(nodes_without_parents) > 0:
                node = random.sample(nodes_without_parents, 1)[0]
            else:
                node = np.random.choice(nodes_single_occurrence, 1)[0]

            node_text = node_texts[node]
            node_id = node_ids[node]
            node_type = NODE_TYPES[node_id]
            edge_to_node = [edge for edge in edge_index if edge[1] == node]

            p = (random.sample(prompts, 1)[0] + random.sample(bots_none, 1) + random.sample(bots_multiple, 1)).copy()
            assert p[2] in bots_none
            p = [s.replace('{graph}', f"{graph_type_map[graph]}").replace('{lang}', f"{lang}") for s in p]

            # deal with answer first in the response before plugging in the node text to avoid replacing something in the code
            num_parents = len(edge_to_node)
            response = p[2] if num_parents == 0 else (p[1] if num_parents == 1 else p[3])
            response = capitalize(response.replace('{node_type}', node_type))

            if num_parents > 1:
                # no problem here
                for j in range(num_parents):
                    parent_node = edge_to_node[j][0]
                    parent_text = node_texts[parent_node]
                    parent_id = node_ids[parent_node]
                    parent_type = NODE_TYPES[parent_id]
                    if '\n' in parent_text:
                        parent_text = f"\n```\n{parent_text}\n```\n"
                        response += f"{parent_type}:{parent_text}"
                    else:
                        parent_text = f"`{parent_text}`"
                        response += f"{parent_type}: {parent_text}\n"
            elif num_parents == 1:
                parent_node = edge_to_node[0][0]
                parent_text = node_texts[parent_node]
                parent_id = node_ids[parent_node]
                parent_type = NODE_TYPES[parent_id]
                if any(parent_type.startswith(l) for l in 'aeio'):
                    response = response.replace(' a ', ' an ')
                if '\n' in parent_text:
                    parent_text = f"\n```\n{parent_text}\n```\n"
                    response = replace_place_holder(response, parent_text, "{parent}")
                else:
                    parent_text = f"`{parent_text}`"
                    response = response.replace('{parent}', parent_text)
                response = response.replace('{parent_type}', parent_type)

            # now deal with node text
            assert response.count('{node}') <= 1
            if '\n' in node_text:
                node_text = f"\n```\n{node_text}\n```\n"
                # note that now response may contain "\n," patterns
                q = replace_place_holder(p[0].replace('{node_type}', node_type), node_text)
                response = replace_place_holder(response, node_text)
            else:
                node_text = f"`{node_text}`"
                q = p[0].replace('{node_type}', node_type).replace('{node}', node_text)
                response = response.replace('{node}', node_text)

            source = source.strip('\n')
            q = f"```\n{source}\n```\n\n{q}"
            question.append(q)
            bot.append(response)
            result.append(num_parents)

        df['question'] = question
        df['bot'] = bot
        graph_dfs.append(df[['node_ids', 'edge_index', 'question', 'bot']])
        results[f"{lang}-{graph}"] = result

"""## Children"""

questions = [
    'In the {graph} of this {lang} program, what are the children of this {node_type}: {node}.',
    'Identify all children of {node_type} {node} in the {graph} of this {lang} program.',
    'Find the child nodes of {node_type} {node} in the {graph} of this {lang} program.',
    'In the {graph} of this {lang} program, how many children does the {node_type} {node} have? What are they?',
    "How many children does {node_type} {node} have in the {graph} of this {lang} program? What are they?",
    'Please find all children of {node_type} {node} in the {graph} of this {lang} program.',
    'Can you find all children of {node_type} {node} in the {graph} of this {lang} program?',
    "List all the descendant nodes of {node_type} {node} in the {graph} of this {lang} program.",
    "What are the direct children of the {node_type} {node} in the {graph} of this {lang} program?",
    "Can you enumerate the offspring of {node_type} {node} within the {graph} of this {lang} program?",
    "Could you provide the list of child nodes attached to {node_type} {node} in the {graph} of this {lang} program?",
    "Please identify the child nodes emanating from {node_type} {node} in the {graph} of this {lang} program.",
    "Show me the child nodes of {node_type} {node} in the {graph} of this {lang} program.",
    "What nodes are directly connected to {node_type} {node} as its children in the {graph} of this {lang} program?",
    "I need to know all the child elements of {node_type} {node} in the {graph} of this {lang} program. Can you provide that?",
    "Are there any nodes that directly derive from {node_type} {node} in the {graph} of this {lang} program?",
    "Which nodes act as successors to the node tagged as {node_type} {node} in the {graph} of this {lang} program?",
    "What are the adjacent nodes that are children of {node_type} {node} in the {graph} of this {lang} program?",
    "Identify the nodes that are immediate successors of {node_type} {node} in the {graph} of this {lang} program.",
    "Detail the nodes branching from {node_type} {node} in the {graph} of this {lang} program.",
    "Reveal all nodes that are directly beneath {node_type} {node} in the topology of the {graph} of this {lang} program.",
]
answers1 = [
    "The given {node_type} has {child_num} children in the {graph}, they are:\n",
    "This {node_type} has {child_num} children:\n",
    "{node_type} {node} has a total of {child_num} children in the {graph}, which are:\n",
    "There are {child_num} child nodes of {node_type} {node}, specifically:\n",
    "As for the children of {node_type} {node}, you will find {child_num} direct descendants:\n",
    "The count of {node_type} {node}'s children amounts to {child_num}. They include:\n",
    "Upon identification, {node_type} {node} appears to have {child_num} offspring, namely:\n",
    "{node_type} {node} is parent to the following {child_num} nodes:\n",
    "A list of the {child_num} children under {node_type} {node} is as follows:\n",
    "Directly under {node_type} {node}, there are {child_num} children listed as:\n",
    "{node_type} {node} holds the hierarchy over {child_num} child nodes, which are:\n",
    "{child_num} children spring from {node_type} {node}, which are given below:\n",
]
answers2 = [
    "This {node_type} does not have any child nodes in the {graph}.",
    "This {node_type} does not have any children in the {graph}.",
    "There are no children of this {node_type} in the {graph} of the given code.",
    "The given {node_type} does not have any children in the {graph}.",
    "After examining the code, it's determined that in the {graph} this {node_type} has no children.",
    "{node_type} {node} stands alone with zero child nodes descending from it.",
    "I've checked the {node_type} {node} and found it has no direct descendants.",
    "There are no child nodes attached to {node_type} {node} in the {graph} of this program.",
    "No descendants can be traced from this {node_type}.",
    "The {node_type} {node} is devoid of child nodes within the {graph} of the code.",
    "Upon inspection, no nodes emerge as children of {node_type} {node}.",
    "{node_type} {node} exists without progeny in the hierarchical layout.",
    "It appears {node_type} {node} has no children.",
]

print(len(questions), len(set(questions)))
print(len(answers1), len(set(answers1)))
print(len(answers2), len(set(answers2)))
assert all(a.count('{answer}') == 1 for a in answers)
assert all(a.count('{graph}') == 1 for a in questions)
assert all(a.count('{lang}') == 1 for a in questions)

bots = [a for a in answers1]
bots_none = [a for a in answers2]
prompts = [[q, b] for q in questions for b in bots]
print(len(prompts))

set_seed(2)

results = {}
for lang, graph in available_combos:
        result = []
        df = pd.read_json(f"{in_dir}/{lang}_{graph}.jsonl", lines=True, nrows=max_rows)
        if lang == 'Python':
            df = filter_df(df)

        question, bot = [], []
        selected_idx = []
        for i in range(len(df)):

            # filter out nodes that occur multiple times in the source code
            node_texts = df.loc[i]['text']
            node_ids = df.loc[i]['node_ids']
            source = df.loc[i]['source']
            edge_index = torch.tensor(df.loc[i]['edge_index'])

            occurrences = np.array([source.count(t) for t in node_texts])
            nodes_single_occurrence = np.where(occurrences == 1)[0]
            nodes_with_children = [n for n in nodes_single_occurrence if n in edge_index[:, 0]]
            nodes_without_children = [n for n in nodes_single_occurrence if n not in edge_index[:, 0]]

            # we roughly maintain a balanced distribution
            if random.random() < 0.85 and len(nodes_with_children) > 0:
                node = random.sample(nodes_with_children, 1)[0]
            elif len(nodes_without_children) > 0:
                node = random.sample(nodes_without_children, 1)[0]
            else:
                node = np.random.choice(nodes_single_occurrence, 1)[0]

            node_text = node_texts[node]
            node_id = node_ids[node]
            node_type = NODE_TYPES[node_id]
            edge_from_node = [edge for edge in edge_index if edge[0] == node]

            p = (random.sample(prompts, 1)[0] + random.sample(bots_none, 1)).copy()
            assert p[1] in bots
            p = [s.replace('{graph}', f"{graph_type_map[graph]}").replace('{lang}', f"{lang}") for s in p]

            num_children = len(edge_from_node)
            if num_children > 10:
                continue
            else:
                selected_idx.append(i)
            response = p[2] if num_children == 0 else p[1]
            response = capitalize(response.replace('{node_type}', node_type))
            if num_children == 1:
                response = response.replace('{child_num}', "1").replace('children', 'child').replace('nodes', 'node').replace('they are', 'it is').replace(' are', ' is').replace('descendants', 'descendant').replace('They include', 'It is').replace(' spring ', ' springs ')
            else:
                response = response.replace('{child_num}', f"{num_children}")

            if '\n' in node_text:
                node_text = f"\n```\n{node_text}\n```\n"
                q = replace_place_holder(p[0].replace('{node_type}', node_type), node_text)
                response = replace_place_holder(response, node_text)
            else:
                node_text = f"`{node_text}`"
                q = p[0].replace('{node_type}', node_type).replace('{node}', node_text)
                response = response.replace('{node}', node_text)

            for j in range(num_children):
                child_node = edge_from_node[j][1]
                child_text = node_texts[child_node]
                child_id = node_ids[child_node]
                child_type = NODE_TYPES[child_id]

                if '\n' in child_text:
                    child_text = f"\n```\n{child_text}\n```\n"
                    response += f"{child_type}:{child_text}"
                else:
                    child_text = f"`{child_text}`"
                    response += f"{child_type}: {child_text}\n"
            if num_children != len(set((node_ids[e[1]], node_texts[e[1]]) for e in edge_from_node)):
                response += "Note that there are multiple children with the same node type and literal representation."

            source = source.strip('\n')
            q = f"```\n{source}\n```\n\n{q}"
            question.append(q)
            bot.append(response)
            result.append(num_children)

        df = df.loc[selected_idx].reset_index(drop=True)
        df['question'] = question
        df['bot'] = bot
        graph_dfs.append(df[['node_ids', 'edge_index', 'question', 'bot']])
        results[f"{lang}-{graph}"] = result

"""## Edge prediction"""

questions = [
    "In the {graph} of this {lang} program, is there {edge_or_link} from {node_type1} {node1} to {node_type2} {node2}?",
    'In the {graph} of this {lang} program, is there {edge_or_link} pointing from {node_type1} {node1} to {node_type2} {node2}?',
    "Please tell me if there is {edge_or_link} pointing from {node_type1} {node1} to {node_type2} {node2} in the {graph} of this {lang} program.",
    'Is there {edge_or_link} from {node_type1} {node1} to {node_type2} {node2} in the {graph} of this {lang} program?',
    "Does a connection exist from {node_type1} {node1} to {node_type2} {node2} in the {graph} of this {lang} program?",
    "In the {graph} of this {lang} program, do we have an arrow leading from {node_type1} {node1} to {node_type2} {node2}?",
    "Is it true that {node_type1} {node1} is a predecessor of {node_type2} {node2} in the {graph} of this {lang} program?",
]
answers1 = [
    "Yes, that is the case.",
    "Yes, there is {edge_or_link} from {node_type1} {node1} to {node_type2} {node2}.",
    "Yes, there is {edge_or_link} from {node_type1} {node1} to {node_type2} {node2} in the {graph} of this code.",
    "Yes, there is {edge_or_link} pointing from {node_type1} {node1} to {node_type2} {node2} in the {graph}.",
    "Affirmative, there exists {edge_or_link} from {node_type1} {node1} to {node_type2} {node2}.",
    "Yes, that is the case. {node1} is directly connected to {node2}.",
]
answers2 = [
    "No, that is not the case.",
    "No, {node_type1} {node1} is not linked to {node_type2} {node2} by any edge in the {graph} of the given code.",
    "No, there is no {edge_or_link} from {node_type1} {node1} to {node_type2} {node2}.",
    "No, such {edge_or_link} is absent from the {graph}.",
    "The code does not show {node_type1} {node1} as a predecessor to {node_type2} {node2} in the {graph}.",
]

print(len(questions), len(set(questions)))
print(len(answers1), len(set(answers1)))
print(len(answers2), len(set(answers2)))
assert all(a.count('{graph}') == 1 for a in questions)
assert all(a.count('{lang}') == 1 for a in questions)

bots = [a for a in answers1]
bots_none = [a for a in answers2]
prompts = [[q, b] for q in questions for b in bots]
print(len(prompts))

set_seed(3)
results = {}
for lang, graph in available_combos:
        result = []
        df = pd.read_json(f"{in_dir}/{lang}_{graph}.jsonl", lines=True, nrows=max_rows)
        if lang == 'Python':
            df = filter_df(df)

        question, bot = [], []
        for i in range(len(df)):

            # filter out nodes that occur multiple times in the source code
            node_texts = df.loc[i]['text']
            node_ids = df.loc[i]['node_ids']
            source = df.loc[i]['source']
            edge_index = df.loc[i]['edge_index']

            occurrences = np.array([source.count(t) for t in node_texts])
            nodes_single_occurrence = np.where(occurrences == 1)[0]
            edge_index_elligible = [e for e in edge_index if (e[0] in nodes_single_occurrence and e[1] in nodes_single_occurrence)]
            if graph == 'AST' and random.random() > 0.1:
                edge_index_elligible = [e for e in edge_index_elligible if (node_texts[e[1]] not in node_texts[e[0]])]

            # we make sure at least half the problems have positive answer
            if random.random() < 0.75 and len(edge_index_elligible) > 0:
                n1, n2 = random.sample(edge_index_elligible, 1)[0]
            else:
                n1, n2 = np.random.choice(nodes_single_occurrence, 2)

            n1_text, n2_text = node_texts[n1], node_texts[n2]
            n1_type, n2_type = NODE_TYPES[node_ids[n1]], NODE_TYPES[node_ids[n2]]

            p = random.sample(prompts, 1)[0] + random.sample(bots_none, 1)
            p = [s.replace('{graph}', f"{graph_type_map[graph]}").replace('{lang}', f"{lang}") for s in p]
            edge_or_link = 'an edge' if random.random() < 0.5 else 'a link'
            p = [s.replace('{edge_or_link}', edge_or_link) for s in p[:-1]] + [p[-1].replace('such {edge_or_link}', f"such {edge_or_link}").replace('{edge_or_link}', edge_or_link.split()[-1])]

            q, b = '', ''
            b = p[1] if [n1, n2] in edge_index else p[2]
            b = b.replace('{node_type1}', n1_type).replace('{node_type2}', n2_type)

            if '\n' in n1_text:
                n1_text = f"\n```\n{n1_text}\n```\n"
                q = replace_place_holder(p[0].replace('{node_type1}', n1_type).replace('{node_type2}', n2_type), n1_text, "{node1}")
                b = replace_place_holder(b, n1_text, "{node1}")
            else:
                n1_text = f"`{n1_text}`"
                q = p[0].replace('{node_type1}', n1_type).replace('{node_type2}', n2_type).replace('{node1}', n1_text)
                b = b.replace('{node1}', n1_text)

            if '\n' in n2_text:
                n2_text = f"\n```\n{n2_text}\n```\n"
                q = replace_place_holder(q, n2_text, "{node2}")
                b = replace_place_holder(b, n2_text, "{node2}")
            else:
                n2_text = f"`{n2_text}`"
                q = q.replace('{node2}', n2_text)
                b = b.replace('{node2}', n2_text)

            source = source.strip('\n')
            q = f"```\n{source}\n```\n\n{q}"
            question.append(q)
            bot.append(b)
            result.append(int([n1, n2] in edge_index))

        df['question'] = question
        df['bot'] = bot
        graph_dfs.append(df[['node_ids', 'edge_index', 'question', 'bot']])
        results[f"{lang}-{graph}"] = result

# Save final output files
os.makedirs(out_dir, exist_ok=True)

# Save instruction_graph.jsonl from graph QA data
graph_df = pd.concat(graph_dfs).reset_index(drop=True)
graph_df.to_json(f"{out_dir}/instruction_graph.jsonl", orient='records', lines=True)
print(f"Saved instruction_graph.jsonl ({len(graph_df)} samples)")

# Save instruction_downstream.jsonl from Java bug-fix data
import json
with open(downstream_buggy) as f:
    buggy = f.readlines()
with open(downstream_fixed) as f:
    fixed = f.readlines()

with open(f"{out_dir}/instruction_downstream.jsonl", 'w') as out:
    for b, fx in zip(buggy[:max_downstream], fixed[:max_downstream]):
        sample = {
            "human": f"# Fix the bug in the following Java program\n\n# Buggy\n{b.strip()}\n\n# Fixed\n",
            "bot": fx.strip()
        }
        out.write(json.dumps(sample) + '\n')
print(f"Saved instruction_downstream.jsonl ({min(max_downstream, len(buggy))} samples)")